### PR TITLE
Implement CI/CD using codemagic

### LINKED ISSUE #2: CI/CD pipelines
- [ ] Implement CI based on Github Actions
- [ ] Implement CD to staging server
- [ ] Get credentials for Codemagic (pending from EBarimt)

### PR DESCRIPTION
**Pull request by endigo**
Close #2 

React Native project-г build хийх эхний тохиргоонуудыг дараах зааврын дагуу хийсэн.
https://docs.codemagic.io/getting-started/building-a-react-native-app/

Github action тохируулах
https://docs.codemagic.io/building/webhooks/

`codemagic.yaml` доторх `Encrypted(...)` хэсгүүдийг [https://docs.codemagic.io/building/encrypting/](https://docs.codemagic.io/building/encrypting/) зааврын дагуу тохируулна уу.

### CODE REVIEW

**Comment by amarbayar** [comment]
Thanks @endigo ! :) 

@zolbooo  @khangaridb  -- Ta 2 neg review hiichih tegehu?

**Comment by zolbooo** [comment]
LGTM, thank you, @endigo 
@amarbayar Codemagic.yaml dotor credentials zaaj uguh heregtei yum bna. Build ni henii developer account deer yvah ve?

**Comment by amarbayar** [comment]
> LGTM, thank you, @endigo
> @amarbayar Codemagic.yaml dotor credentials zaaj uguh heregtei yum bna. Build ni henii developer account deer yvah ve?

Nuguu `Exposure Notification API` entitlement avch baigaa account dor yavna. Ter zuvshuurliig ebarimt deer avhuulj baigaa bolhoor tednii account deer yavah baih. cc

**Comment by zolbooo** [comment]
Okay, tegvel #2 deer comment nemeed merge hiilee.

**Pull request merged**
